# Generated by Django 5.2.9 on 2026-01-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Фото сотрудника (необязательно)",
                null=True,
                upload_to="avatars/",
                verbose_name="Аватарка",
            ),
        ),
    ]
