# Generated by Django 5.2.9 on 2026-01-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["display_order", "full_name"],
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="display_order",
            field=models.IntegerField(
                blank=True,
                help_text="Число для указания порядка отображения сотрудника в списке. Меньшее число = выше в списке. Если не указано, сортировка по алфавиту.",
                null=True,
                verbose_name="Порядок отображения",
            ),
        ),
    ]
