# Generated by Django 5.2.9 on 2026-01-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contact_options_contact_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="avatar_cropping",
            field=models.CharField(
                blank=True,
                help_text="Координаты обрезки изображения",
                max_length=255,
                verbose_name="Обрезка аватарки",
            ),
        ),
    ]
