# Generated by Django 5.2.9 on 2026-01-13 12:18

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_contact_avatar_cropping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="avatar_cropping",
            field=image_cropping.fields.ImageRatioField(
                "avatar",
                "400x400",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=True,
                help_text="Выберите область для обрезки изображения. Рекомендуемый размер: 400x400 пикселей",
                hide_image_field=False,
                size_warning=True,
                verbose_name="Обрезка аватарки",
            ),
        ),
    ]
