# Generated by Django 5.2.9 on 2026-01-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_alter_contact_avatar_cropping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["display_order", "name_ru"],
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отделы",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="display_order",
            field=models.IntegerField(
                blank=True,
                help_text="Число для указания порядка отображения отдела в списке. Меньшее число = выше в списке. Если не указано, сортировка по алфавиту.",
                null=True,
                verbose_name="Порядок отображения",
            ),
        ),
    ]
