# Generated by Django 5.2.9 on 2026-01-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_alter_department_options_department_display_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True,
                        max_length=300,
                        verbose_name="Название вакансии (русский)",
                    ),
                ),
                (
                    "title_kk",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Название вакансии (казахский)",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Описание вакансии (русский)",
                    ),
                ),
                (
                    "description_kk",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Описание вакансии (казахский)",
                    ),
                ),
                (
                    "requirements_ru",
                    models.TextField(
                        blank=True,
                        help_text="Требования к кандидату",
                        null=True,
                        verbose_name="Требования (русский)",
                    ),
                ),
                (
                    "requirements_kk",
                    models.TextField(
                        blank=True,
                        help_text="Требования к кандидату",
                        null=True,
                        verbose_name="Требования (казахский)",
                    ),
                ),
                (
                    "conditions_ru",
                    models.TextField(
                        blank=True,
                        help_text="Условия работы, график и т.д.",
                        null=True,
                        verbose_name="Условия работы (русский)",
                    ),
                ),
                (
                    "conditions_kk",
                    models.TextField(
                        blank=True,
                        help_text="Условия работы, график и т.д.",
                        null=True,
                        verbose_name="Условия работы (казахский)",
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        help_text="Email, телефон или другая контактная информация для отклика",
                        max_length=500,
                        null=True,
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Показывать ли вакансию в списке и на сайте",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        blank=True,
                        help_text="Число для сортировки вакансий в списке. Меньшее число = выше в списке. Если не указано, сортировка по дате создания.",
                        null=True,
                        verbose_name="Порядок отображения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancies",
                        to="contacts.department",
                        verbose_name="Отдел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["title_ru", "is_active"],
                        name="contacts_va_title_r_096a85_idx",
                    ),
                    models.Index(
                        fields=["department", "is_active"],
                        name="contacts_va_departm_8f860b_idx",
                    ),
                ],
            },
        ),
    ]
