# Generated by Django 5.2.10 on 2026-01-15 05:22

from django.db import migrations, models


def merge_requirements_and_conditions(apps, schema_editor):
    """
    Объединяет данные из полей requirements и conditions в новое поле requirements_and_conditions.
    Сохраняет существующие данные при миграции.
    """
    Vacancy = apps.get_model('contacts', 'Vacancy')
    for vacancy in Vacancy.objects.all():
        # Объединяем требования и условия для русского языка
        parts_ru = []
        if vacancy.requirements_ru:
            parts_ru.append(vacancy.requirements_ru)
        if vacancy.conditions_ru:
            parts_ru.append(vacancy.conditions_ru)
        if parts_ru:
            vacancy.requirements_and_conditions_ru = '\n\n'.join(parts_ru)
        
        # Объединяем требования и условия для казахского языка
        parts_kk = []
        if vacancy.requirements_kk:
            parts_kk.append(vacancy.requirements_kk)
        if vacancy.conditions_kk:
            parts_kk.append(vacancy.conditions_kk)
        if parts_kk:
            vacancy.requirements_and_conditions_kk = '\n\n'.join(parts_kk)
        
        vacancy.save()


def reverse_merge(apps, schema_editor):
    """
    Обратная миграция: разделяем requirements_and_conditions обратно на requirements и conditions.
    """
    Vacancy = apps.get_model('contacts', 'Vacancy')
    for vacancy in Vacancy.objects.all():
        # Для простоты обратной миграции просто копируем данные в requirements
        # (полное восстановление невозможно без дополнительной логики)
        if vacancy.requirements_and_conditions_ru:
            vacancy.requirements_ru = vacancy.requirements_and_conditions_ru
        if vacancy.requirements_and_conditions_kk:
            vacancy.requirements_kk = vacancy.requirements_and_conditions_kk
        vacancy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_vacancy'),
    ]

    operations = [
        # Сначала добавляем новые поля
        migrations.AddField(
            model_name='vacancy',
            name='requirements_and_conditions_kk',
            field=models.TextField(blank=True, help_text='Требования к кандидату и условия работы', null=True, verbose_name='Требования и условия (казахский)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_and_conditions_ru',
            field=models.TextField(blank=True, help_text='Требования к кандидату и условия работы', null=True, verbose_name='Требования и условия (русский)'),
        ),
        # Копируем данные из старых полей в новые
        migrations.RunPython(merge_requirements_and_conditions, reverse_merge),
        # Удаляем старые поля
        migrations.RemoveField(
            model_name='vacancy',
            name='conditions_kk',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='conditions_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements_kk',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements_ru',
        ),
    ]
