# Generated by Django 5.2.10 on 2026-01-15 06:40

import django.db.models.deletion
from django.db import migrations, models


def migrate_titles_to_positions(apps, schema_editor):
    """
    Переносит данные из полей title_ru и title_kk в должности (Position).
    Создает должности на основе названий вакансий и связывает их.
    """
    Vacancy = apps.get_model('contacts', 'Vacancy')
    Position = apps.get_model('contacts', 'Position')
    
    for vacancy in Vacancy.objects.all():
        if vacancy.title_ru:
            # Создаем или получаем должность на основе title_ru
            position, created = Position.objects.get_or_create(
                name_ru=vacancy.title_ru,
                defaults={
                    'name_kk': vacancy.title_kk or '',
                }
            )
            vacancy.position = position
            vacancy.save()


def reverse_migrate_positions_to_titles(apps, schema_editor):
    """
    Обратная миграция: копирует название должности обратно в title_ru.
    """
    Vacancy = apps.get_model('contacts', 'Vacancy')
    
    for vacancy in Vacancy.objects.all():
        if vacancy.position:
            vacancy.title_ru = vacancy.position.name_ru
            vacancy.title_kk = vacancy.position.name_kk or ''
            vacancy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_vacancy_conditions_kk_and_more'),
    ]

    operations = [
        # Сначала удаляем старый индекс
        migrations.RemoveIndex(
            model_name='vacancy',
            name='contacts_va_title_r_096a85_idx',
        ),
        # Добавляем новое поле position (nullable)
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Должность для вакансии. Позволяет фильтровать вакансии по должностям.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='contacts.position', verbose_name='Должность'),
        ),
        # Переносим данные из title в position
        migrations.RunPython(migrate_titles_to_positions, reverse_migrate_positions_to_titles),
        # Удаляем старые поля
        migrations.RemoveField(
            model_name='vacancy',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title_ru',
        ),
        # Добавляем новый индекс
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['position', 'is_active'], name='contacts_va_positio_87bdde_idx'),
        ),
    ]
