# Generated by Django 5.2.10 on 2026-01-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_remove_vacancy_contacts_va_title_r_096a85_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['display_order', 'type', 'name_ru'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('department', 'Департамент'), ('division', 'Отдел/Управление'), ('management', 'Руководство')], default='division', help_text='Департамент - верхний уровень, Отдел - входит в департамент, Руководство - без привязки', max_length=20, verbose_name='Тип подразделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название подразделения (казахский)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Название подразделения (русский)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Укажите департамент, если это отдел. Оставьте пустым для департамента или руководства.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='contacts.department', verbose_name='Родительский департамент/отдел'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['type', 'parent'], name='contacts_de_type_521909_idx'),
        ),
    ]
