# Generated by Django 5.2.10 on 2026-01-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_alter_department_options_department_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['display_order', 'employment_type', 'full_name'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contact',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Штатный сотрудник'), ('part_time', 'Совместитель'), ('external', 'Внештатный сотрудник'), ('contract', 'По договору')], db_index=True, default='full_time', help_text='Тип трудоустройства сотрудника (штатный, внештатный и т.д.)', max_length=20, verbose_name='Тип трудоустройства'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['employment_type', 'department'], name='contacts_co_employm_0833ff_idx'),
        ),
    ]
