# Generated by Django 5.2.10 on 2026-01-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_contact_options_contact_employment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(db_index=True, max_length=300, verbose_name='Название отдела (русский)')),
                ('name_kk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название отдела (казахский)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('display_order', models.IntegerField(blank=True, help_text='Число для указания порядка отображения отдела в списке. Меньшее число = выше в списке.', null=True, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['display_order', 'name_ru'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['display_order', 'employment_type', 'full_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['display_order', 'type', 'name_ru'], 'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_employm_0833ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='contacts_de_type_521909_idx',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Департамент (если сотрудник привязан напрямую к департаменту, а не к отделу)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='department',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Число для указания порядка отображения департамента в списке. Меньшее число = выше в списке.', null=True, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название департамента (казахский)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Название департамента (русский)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('department', 'Департамент'), ('management', 'Руководство')], default='department', help_text='Департамент - обычное подразделение, Руководство - верхний уровень управления', max_length=20, verbose_name='Тип департамента'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Департамент (если вакансия на уровне департамента)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='contacts.department', verbose_name='Департамент'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['type'], name='contacts_de_type_b05766_idx'),
        ),
        migrations.AddField(
            model_name='division',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Департамент, к которому относится отдел. Может быть пустым для независимых отделов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='contacts.department', verbose_name='Департамент'),
        ),
        migrations.AddField(
            model_name='contact',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Отдел, к которому относится сотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.division', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Отдел, в котором открыта вакансия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='contacts.division', verbose_name='Отдел'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['division', 'position'], name='contacts_co_divisio_cff92f_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['employment_type', 'division'], name='contacts_co_employm_16f456_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['division', 'is_active'], name='contacts_va_divisio_8a46cc_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['name_ru'], name='contacts_di_name_ru_95aedd_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['department'], name='contacts_di_departm_827fce_idx'),
        ),
    ]
