# Generated by Django 5.2.10 on 2026-01-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_division_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['display_order', 'name_ru'], 'verbose_name': 'Управление', 'verbose_name_plural': 'Управления'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Департамент (если сотрудник привязан напрямую к департаменту, а не к управлению)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Управление, к которому относится сотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.division', verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Название отдела (русский)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('department', 'Департамент'), ('management', 'Руководство')], db_index=True, default='department', help_text='Департамент - обычное подразделение, Руководство - верхний уровень управления', max_length=20, verbose_name='Тип департамента'),
        ),
        migrations.AlterField(
            model_name='division',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Департамент, к которому относится управление. Может быть пустым для независимых управлений.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='contacts.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='division',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Число для указания порядка отображения управления в списке. Меньшее число = выше в списке.', null=True, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название управления (казахский)'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Название управления (русский)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Управление, в котором открыта вакансия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='contacts.division', verbose_name='Управление'),
        ),
    ]
