# Generated by Django 5.2.10 on 2026-01-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_division_options_alter_contact_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['display_order', 'type', 'name_ru'], 'verbose_name': 'Департамент/Комитет', 'verbose_name_plural': 'Департаменты/Комитеты'},
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Связь с учетной записью пользователя для доступа к чату', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Департамент/комитет (если сотрудник привязан напрямую к департаменту, а не к управлению)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.department', verbose_name='Департамент/Комитет'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название департамента/комитета (казахский)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Название департамента/комитета (русский)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('department', 'Департамент/Комитет'), ('management', 'Руководство')], db_index=True, default='department', help_text='Департамент - обычное подразделение, Руководство - верхний уровень управления', max_length=20, verbose_name='Тип департамента'),
        ),
        migrations.AlterField(
            model_name='division',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Департамент/комитет, к которому относится управление. Может быть пустым для независимых управлений.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='contacts.department', verbose_name='Департамент/Комитет'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Департамент/комитет (если вакансия на уровне департамента)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='contacts.department', verbose_name='Департамент/Комитет'),
        ),
    ]
