# Generated by Django 5.2.11 on 2026-02-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_alter_department_options_contact_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата рождения сотрудника (для отображения в календаре дней рождения)', null=True, verbose_name='Дата рождения'),
        ),
    ]
