# Generated by Django 5.2.10 on 2026-01-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_contact_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='chat_access',
            field=models.BooleanField(default=True, help_text='Если выключено, сотрудник не будет отображаться в списке чатов, и сам не сможет пользоваться чатом.', verbose_name='Доступ к чату'),
        ),
    ]
