version: '3.8'

services:
  hr-guide-web:
    build: .
    container_name: hr-guide-web
    restart: unless-stopped
    # Добавлен --noreload для скорости в локальной сети
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/app
      - ./media:/app/media
      # Поменяйте эту строку:
      - ./staticfiles:/app/staticfiles
    ports:
      - "8880:8000"
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DATABASE_HOST=${DATABASE_HOST:-postgres}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_NAME=${DATABASE_NAME:-hr-guide}
      - DATABASE_USER=${DATABASE_USER:-admin}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-Postgres9007}
    networks:
      - hr-guide-network
      - database_network

volumes:
  hr-guide-staticfiles:
    driver: local

networks:
  hr-guide-network:
    driver: bridge
  database_network:
    external: true
    name: database_network