# Generated by Django 5.2.10 on 2026-01-23 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата последнего сообщения')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли чат', verbose_name='Активен')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_participant1', to=settings.AUTH_USER_MODEL, verbose_name='Участник 1')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_participant2', to=settings.AUTH_USER_MODEL, verbose_name='Участник 2')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chat', verbose_name='Чат')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл будет автоматически удален через 30 дней', upload_to='chat_files/%Y/%m/%d/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байты)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME-тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата загрузки')),
                ('delete_after', models.DateTimeField(db_index=True, help_text='Дата, после которой файл будет удален (30 дней после загрузки)', verbose_name='Удалить после')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['participant1', 'participant2'], name='messaging_c_partici_8b9960_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['last_message_at'], name='messaging_c_last_me_280909_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('participant1', 'participant2')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='messaging_m_chat_id_6e08b6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='messaging_m_sender__277197_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='messaging_m_is_read_8b9e91_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['message', 'uploaded_at'], name='messaging_f_message_bb3f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['delete_after'], name='messaging_f_delete__3d2d94_idx'),
        ),
    ]
