# Generated by Django 5.2.11 on 2026-02-03 20:40

from django.db import migrations

def migrate_participants(apps, schema_editor):
    Chat = apps.get_model('messaging', 'Chat')
    ChatParticipant = apps.get_model('messaging', 'ChatParticipant')
    
    for chat in Chat.objects.all():
        if chat.participant1:
            ChatParticipant.objects.get_or_create(
                chat=chat, 
                user=chat.participant1,
                defaults={'role': 'member'}
            )
        if chat.participant2:
            ChatParticipant.objects.get_or_create(
                chat=chat, 
                user=chat.participant2,
                defaults={'role': 'member'}
            )

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_chatparticipant_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_participants, reverse_migrate),
    ]