# Generated by Django 5.2.11 on 2026-02-05 05:46

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kk', models.CharField(help_text='Заголовок объявления на казахском языке', max_length=255, verbose_name='Заголовок (каз)')),
                ('title_ru', models.CharField(help_text='Заголовок объявления на русском языке', max_length=255, verbose_name='Заголовок (рус)')),
                ('content_kk', ckeditor.fields.RichTextField(help_text='Содержимое объявления на казахском языке с форматированием', verbose_name='Содержимое (каз)')),
                ('content_ru', ckeditor.fields.RichTextField(help_text='Содержимое объявления на русском языке с форматированием', verbose_name='Содержимое (рус)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании объявления', verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(help_text='Пользователь, создавший объявление', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='announcement_created_idx')],
            },
        ),
    ]
